### ISSUE TITLE
why normal db query shows data in plain text along with encrypted column?

### ISSUE THREAD

**Issue by jaswinder97** [hashicorp/vault-rails#100]
=> #<Insured:0x0000562a3343c890
 id: 51,
 source_type: "primary",
 first_name: "jas",
 last_name: "saini",
 middle_name: "singh",
 us_citizen: true,
 quote_id: 22635,
 **driving_license_number****: "JAW1231231",**
 ssn: "Yes",
 ssn_encrypted: "vault:v1:v1vr0WvE1Az8hG8vQ+dH6wdv6zjHV8TtCnYS8Xr2Mw==",
 **driving_license_number_encrypted: "vault:v1:11O+qO+8CelPV+p5bwJdlvxlcA/xAvIt4thfO3J9zAEr/fclq3w=">**

**Comment by fatfrog** [comment]
I'm also having this problem.  My data is encrypted, but I can't clear out the un-encrypted column without clearing out the encrypted column and I have both encrypted and non-encrypted versions in my database.

**Comment by jaswinder97** [comment]
@fatfrog I was able to fix it. Actually I misunderstood how we should accept the column data.

In the DB, we just need a column with suffix `_encrypted`

so we don't need both columns like `ssn` and `ssn_encrypted` , just remove the unencrypted one.

then in the rails app just use the column as `ssn`, for example in strong params:   `:ssn`
make sure we declare this vault attribute in the model itself

**Comment by fatfrog** [comment]
Ah, that make way more sense.  You didn't misunderstand the documentation - it wasn't very clear.  Step 3 looks like you need to have both an ssn and ssn_encrypted column.  Thanks for your help!

**Comment by chrisarcand** [comment]
An extra bit of info was added in https://github.com/hashicorp/vault-rails/commit/99fe80bbaea559d5caf5945f70a195cd35ea6ae6 which hopefully clarifies this; please feel free to submit a PR if it doesn't. Thanks! 🙇🏻‍♂️
