### ISSUE TITLE
v0.1.2 is outdated

### ISSUE THREAD

**Issue by guymaliar** [hashicorp/vault-rails#13]
The README does not work for v0.1.2 :-)

`Vault::Rails.configure method not found`

**Comment by sethvargo** [comment]
Hi @guymaliar 

The README is not "outdated", but rather the README corresponds to the master branch of the project. If you want the documentation for a specific version, you can [browse that tag](https://github.com/hashicorp/vault-rails/tree/d529ae3e429a018a25d54c8c27883dfec3866933) and view the README there. Thanks!
