### ISSUE TITLE
Should vault-rails really require rails?

### ISSUE THREAD

**Issue by BRMatt** [hashicorp/vault-rails#18]
I appreciate this sounds a bit strange, but looking through the code it seems that the only part of rails that `vault-rails` requires is `ActiveSupport`, as the `ActiveRecord` specific stuff is [nicely localised and hidden behind a `defined?` check](https://github.com/hashicorp/vault-rails/blob/c508e3553321b9457e7f08755602e9b8df462401/lib/vault/encrypted_model.rb#L157-L173). 

Most of our internal services are only small sinatra json-only APIs, and adding the vault gem brings in quite a few unnecessary dependencies, such as sprockets(!). (To be honest, the only parts of `vault-rails` we use are `Vault::Rails.encrypt`/`Vault::Rails.decrypt`, as we need to use different encryption keys depending on the record's attributes).

Would you mind if I submit a PR to replace the `rails` dependency with `activesupport`?

**Comment by sethvargo** [comment]
@BRMatt 

If you're only using the `Vault::Rails.encrypt/decrypt` functions, why not just use the vault-ruby client directly. It's only saving you like 5 lines of code to use vault-rails. What benefits does vault-rails provide that vault-ruby doesnt?

**Comment by BRMatt** [comment]
That's a fair point. The main reason was the convenience of the in-memory implementations of those functions, which didn't seem to be present in the `vault-ruby` library. We have about 4-5 internal services that need to use vault, and this gem made it is easy to drop in vault without rewriting the tests to drop in/fake out the vault client.

**Comment by sethvargo** [comment]
@BRMatt 

The issue with dropping the rails requirement is that we still need it for a dev dep. I guess I don't _really_ care, but this seems like overkill for your particular use case. I'd be happy to review a PR :smile:
