### ISSUE TITLE
undefined method `application='

### ISSUE THREAD

**Issue by lubekpl** [hashicorp/vault-rails#20]
Hi,

I'm having configuration problems, please advise ;)

My initializer
```
require "vault/rails"
Vault.configure do |vault|
  vault.application = "my_app"
  vault.address = ENV["VAULT_ADDR"]
  vault.token = ENV["VAULT_TOKEN"]
end
```

```...config/initializers/vault.rb:4:in `block in <top (required)>': undefined method `application=' for #<Vault::Client:0x007fb76be496c8> (NoMethodError)```

I'm using 
```
vault (0.1.5)
vault-rails (0.1.2)
```
with Ruby 2.1.5 and rails 4.1.9

**Comment by sethvargo** [comment]
Hi @lubekpl 

This has been fixed on master and you need to use `Vault::Rails` instead of `Vault`. Could you please try pulling in from GitHub via bundler?

**Comment by lubekpl** [comment]
Hello @sethvargo,

works like a charm :+1:
