### ISSUE TITLE
Question: Conditional encrypt

### ISSUE THREAD

**Issue by assimovt** [hashicorp/vault-rails#30]
Hey. Just a quick question.

Is there any way to conditionally encrypt data, for instance, I want to achieve something like this:

```ruby
    vault_attribute :data, if: proc { |o| o.confidential? }
```

Behind the scenes, it would work the same but not touch Vault.

**Comment by sethvargo** [comment]
Hi @assimovt 

Thank you for opening an issue. This is not something that is currently supported, and it's not something I envision us supporting. You can disable encryption globally (for testing/dev) in the initializer, but I don't think it's a good practice to conditionally encrypt data. The columns in the database are either confidential or they are not, and I think it's safer just to encrypt everything :smile:

**Comment by assimovt** [comment]
Alright, thanks for reply.
