### ISSUE TITLE
require 'vault/rails/testing' Throws a LoadError

### ISSUE THREAD

**Issue by jgoodell** [hashicorp/vault-rails#33]
Following the documentation for 0.1.2 to enable the in-memory store for testing.

```ruby
require "vault/rails/testing"
Vault::Rails::Testing.enable!
```

But I encounter a LoadError when trying to require. I've double and triple checked that the correct version of vault-rails is installed.

```
vagrant@norad-dev-box:~/api$ bundle list
...
 * vault-rails (0.1.2 6aea0e6)
  * vegas (0.1.11)
  * will_paginate (3.1.0)
vagrant@norad-dev-box:~/api$ bundle exec irb
2.3.0 :001 > require 'vault/rails/testing'
LoadError: cannot load such file -- vault/rails/testing
        from (irb):1:in 'require'
        from (irb):1
        from /home/vagrant/.rvm/rubies/ruby-2.3.0/bin/irb:11:in '<main>'
2.3.0 :002 > require 'vault/rails'
 => true
2.3.0 :003 > exit
```

**Comment by sethvargo** [comment]
Hi @jgoodell 

You are using a version of Vault rails from a git sha, which is actually using a different version. There is no need to require testing mode anymore, it's included by default.
