### ISSUE TITLE
Support for Rails 5

### ISSUE THREAD

**Issue by truevy** [hashicorp/vault-rails#35]
Can you implement support for Rails 5?

**Comment by assimovt** [comment]
In the meanwhile, I am using [Dockbit/vault-rails](https://github.com/Dockbit/vault-rails/tree/rails5) fork with Rails 5 support.

**Comment by sethvargo** [comment]
Is there something in particular that needs to change for that support?

**Comment by assimovt** [comment]
I only had to change gemspec and dummy app to make the tests pass, see [single commit](https://github.com/Dockbit/vault-rails/commit/d9fdd2db846740ef7f10217f5d1bc5c86526ed98)

**Comment by truevy** [comment]
Thanks!
