### ISSUE TITLE
Use this to get initial application secrets

### ISSUE THREAD

**Issue by akshah123** [hashicorp/vault-rails#49]
Is it possible to use this project to store application secrets that are usually kept in secrets.yml file? If so, it would be great if an example was provided in readme.

**Comment by sethvargo** [comment]
Hi @akshah123 

This project is used to encrypt/decrypt fields in ActiveRecord. It cannot be used to query for settings at startup without a custom integration. I would recommend looking at [consul-template](https://github.com/hashicorp/consul-template) or [envconsul](https://github.com/hashicorp/envconsul) to do that. Thanks! 😄
