### ISSUE TITLE
Check for uniqueness of vault_attribute

### ISSUE THREAD

**Issue by kjakub** [hashicorp/vault-rails#52]
I am aware that it is not possible to search on encrypted columns - stated in README.md. However i am trying to use vault-rails and devise and therefore i need to check for uniqueness of email. First I thought that something like

`validates_uniqueness_of :email_encrypted`

will work, but nope. I can see 

```
INSERT INTO "users"...
UPDATE "users" SET "email_encrypted"
```

so i came up with 

```
  after_save :validates_email_uniquenes

  def validates_email_uniquenes
    unless self.class.where(email_encrypted: self.email_encrypted).where.not(id: self.id).empty?
      self.errors.add(:email, "Email taken")
      raise ActiveRecord::Rollback
    end
  end
```
from the first look it works, however can i rely on email_encrypted in every case ? (upgrading vault instance, migrating vault instance, etc ? )

**Comment by sethvargo** [comment]
Hi there,

Vaults transit backend does not support [convergent encryption](https://wikipedia.org/wiki/Convergent_encryption), thus the same plaintext value does *not* encrypt into the same ciphertext. You can test this yourself by sending the same plaintext data to vault twice - you’ll get a different ciphertext. 

“Uniqueness” is a property that is a result of a search, and it’s not possible to search until vault supports convergent encryption. Sorry!

**Comment by kjakub** [comment]
@sethvargo Thank you very much for clarification. However i am getting same ciphertext with `./vault server -dev` production mode will differ ?

**Comment by sethvargo** [comment]
Hi @kjakub 

I'm not sure how you've configured Vault, but it returns different values:

```
➜  ~  vault server -dev
# ... 

➜  ~  vault mount transit
Successfully mounted 'transit' at 'transit'!

➜  ~  vault write -f transit/keys/foo
Success! Data written to: transit/keys/foo

➜  ~  vault write transit/encrypt/foo plaintext=$(base64 <<< "hi")
Key       	Value
---       	-----
ciphertext	vault:v1:7YwpPbXdmEmLtT+KGJTuJduVVv7be1Ei+IWI46Uvhg==

➜  ~  vault write transit/encrypt/foo plaintext=$(base64 <<< "hi")
Key       	Value
---       	-----
ciphertext	vault:v1:bj+BG1gjK7jYfxQJqYxYt6ixjSSuHCXxNWe/bfdwAw==

➜  ~  vault write transit/encrypt/foo plaintext=$(base64 <<< "hi")
Key       	Value
---       	-----
ciphertext	vault:v1:Ouh04OKHMF4P5fF7Os59M4/nmGnwLdwFV/C5BYuZhg==
```

**Comment by kjakub** [comment]
Thank you for your patience. I am new to vault, i have not configured more than [Getting started](https://www.vaultproject.io/intro/getting-started/install.html) guide say. 

```
class User < ApplicationRecord 
  include Vault::EncryptedModel
  vault_attribute :email
  .....
end
```
and then 

```
2.3.1 :189 > u = User.new
 => #<User id: nil, created_at: nil, updated_at: nil, ...> 
2.3.1 :190 > u.email = "jakub.kuchar@hotmail.com"
 => "jakub.kuchar@hotmail.com" 
2.3.1 :191 > u.password = "password"
2.3.1 :191 > u.save
```

repeat with same email

```
2.3.1 :189 > u = User.new
 => #<User id: nil, created_at: nil, updated_at: nil, ...> 
2.3.1 :190 > u.email = "jakub.kuchar@hotmail.com"
 => "jakub.kuchar@hotmail.com" 
2.3.1 :191 > u.password = "password"
2.3.1 :191 > u.save
```

```
2.3.1 :194 > User.all.map(&:email_encrypted)
  User Load (1.0ms)  SELECT "users".* FROM "users"
[vault-rails] Using in-memory cipher - this is not secure and should never be used in production-like environments!
[vault-rails] Using in-memory cipher - this is not secure and should never be used in production-like environments!
 => ["b3/zEeFWMeyHWImzVxzeWoPJWA/mqgpspiC7ac9N4Nk=", "b3/zEeFWMeyHWImzVxzeWoPJWA/mqgpspiC7ac9N4Nk="]
```

**Comment by kjakub** [comment]
ok @sethvargo thank you for being with me. I run vault as production + consul and rails vault initializer with 

```
  # Use Vault in transit mode for encrypting and decrypting data. If
  # disabled, vault-rails will encrypt data in-memory using a similar
  # algorithm to Vault. The in-memory store uses a predictable encryption
  # which is great for development and test, but should _never_ be used in
  # production.
vault.enabled = true
```
and getting DIFFERENT ciphertexts for SAME emails.

And can confirm that with `vault.enabled = false` resulting into getting SAME ciphertexts for SAME values (emails).

**Comment by sethvargo** [comment]
Hi @kjakub 

Yes - as the note indicates - in "development" mode, you're not hitting a real Vault server. It only exists at the Ruby layer.
