### ISSUE TITLE
ArgumentError: key must be 16 bytes

### ISSUE THREAD

**Issue by mycraftmw** [hashicorp/vault-rails#54]
Hello, I get an error message: ArgumentError: key must be 16 bytes after I try to save the data, therefore I cannot save data into the database. What can I do?

**Comment by rbhitchcock** [comment]
Hi @mycraftmw! Could you please provide what version of Rails, Ruby, and vault-rails you are trying to use?

**Comment by mycraftmw** [comment]
Sure. Here are the things: Rails 5.1.4, ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux] and vault-rails-0.3.2.

**Comment by rbhitchcock** [comment]
In short, older versions of vault-rails are not compatible with Ruby 2.4. You'll need to upgrade to version 0.4.0 of vault-rails. You can find more info here: https://github.com/hashicorp/vault-rails/pull/50

**Comment by mycraftmw** [comment]
Oh, I see. Thank you very much for your patience.

**Comment by gdemonie** [comment]
Hi, any intention to make the gem compatible with rails 5.1 any time soon? Thanks!
