### ISSUE TITLE
Support for Ruby 2.5/2.6

### ISSUE THREAD

**Issue by therealrodk** [hashicorp/vault-rails#68]
My current app uses Ruby 2.5.1 and I have heard that 2.6 is around the corner. It would be nice to see support for these versions. Thanks!

**Comment by michaelsalexander83** [comment]
Would also love to use this in my application.
Any updates on this?

**Comment by justincampbell** [comment]
Yes! This gem is tested against Ruby 2.4, 2.5, and 2.6 latest patch versions. Let us know if you have any issues running it on a supported Ruby version.
