### ISSUE TITLE
Creating object via nested attributes with encrypted columns

### ISSUE THREAD

**Issue by kjakub** [hashicorp/vault-rails#70]
Creating object via nested attributes, where nested attributes are defined in child model as `vault_attribute :column_name` are all empty after creation. 

bank_number is encrypted
bank_name is not encrypted

inverse_of: is set correctly both on parent and child

Need to reload object in order to get attributes

````
parent = Parent.create!({parent_name:"Client Name", child_attributes: {bank_number:"12", bank_name: "Big Bank"} })

parent.child.bank_number == nil
true
parent.child.bank_name == nil
false

parent.reload
parent.child.bank_number == nil
false

**Comment by kjakub** [comment]
after my findings, this behavior/bug? is not related to vault-rails gem itself but rather to `update_column` method in `after_save` callback in rails framework.  However but i feel personal necessity to share it here since it can easily bite someone else too. 

I fork this repository and extend dummy app with Parent and Kid models in order to prove its existence via running spec. In Parent and Kid i added color attribute as well to prove that it is not related to the gem itself.

[https://travis-ci.org/kjakub/vault-rails](https://travis-ci.org/kjakub/vault-rails)

`rspec spec/integration/rails_spec.rb --tag dev:kid_first`

and then if you like see it fail with following

[https://github.com/kjakub/vault-rails/blob/master/spec/dummy/app/models/parent.rb#L7](https://github.com/kjakub/vault-rails/blob/master/spec/dummy/app/models/parent.rb#L7)

**Comment by Valarissa** [comment]
Is this still an issue with PR #67 now merged? Let me know so we can potentially close this out.
